### ISSUE TITLE
Switch to qcircle-design-template

### ISSUE THREAD

**Issue by yoavst** [zsoltmester/qcn#1]
LG developers have created this library for make Quick Circle apps easy - https://github.com/LGDeveloper/QCircle-Design-Template

Your code will be shorter and easier to maintain

**Comment by zsoltmester** [comment]
I do not need anything from that template. I have material back btn and I do not need title, side etc.

**Comment by yoavst** [comment]
In most of my modules I use it mostly for layout the circle. You have created a base class for it, https://github.com/zsoltmester/qcn/blob/master/app/src/main/java/zsoltmester/qcn/qc/QCBaseActivity.java . I think it is better to use their template because when the api will change/ need to add code for another size devices, their template will be updated, and it is a lot easier.

**Comment by zsoltmester** [comment]
Oh, it is sounds good. I will update when I think I want to support another devices. Currently I just want to support g3. Thanks!
